#!/bin/bash

set -euo pipefail

# Host-side restore script for images generated by backup.sh
# Designed for Ubuntu 20.04 and compatible GNU coreutils/findutils.

DEFAULT_BACKUP_DIR="/mnt/backup"
BACKUP_DIR="${BACKUP_DIR:-$DEFAULT_BACKUP_DIR}"

SYSTEM_DEVICE="${SYSTEM_DEVICE:-}"
DATA_DEVICE="${DATA_DEVICE:-}"
ENABLE_DATA_RESTORE="${ENABLE_DATA_RESTORE:-no}"    # auto|yes|no
STRICT_CHECKSUM="${STRICT_CHECKSUM:-yes}"          # yes|no
ASSUME_YES="${ASSUME_YES:-no}"                     # yes|no

SYSTEM_IMG="${SYSTEM_IMG:-}"
DATA_IMG="${DATA_IMG:-}"

DATE="$(date +%F_%H-%M-%S)"
LOG_FILE="${LOG_FILE:-$BACKUP_DIR/host_restore_${DATE}.log}"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

error_exit() {
    log "ERROR: $1"
    exit 1
}

require_command() {
    local cmd=$1
    if ! command -v "$cmd" >/dev/null 2>&1; then
        error_exit "Missing dependency: $cmd"
    fi
}

check_dependencies() {
    local cmds=(dd gunzip gzip md5sum find blockdev lsblk awk grep sed tee)
    local c
    for c in "${cmds[@]}"; do
        require_command "$c"
    done
}

check_backup_dir() {
    [ -d "$BACKUP_DIR" ] || error_exit "BACKUP_DIR not found: $BACKUP_DIR"
    [ -r "$BACKUP_DIR" ] || error_exit "BACKUP_DIR not readable: $BACKUP_DIR"
}

find_latest_image() {
    local pattern=$1
    local latest

    latest=$(find "$BACKUP_DIR" -maxdepth 1 -type f -name "$pattern" -printf '%T@ %p\n' \
        | sort -nr \
        | awk 'NR==1 {$1=""; sub(/^ /, ""); print}')

    if [ -n "$latest" ] && [ -f "$latest" ]; then
        echo "$latest"
        return 0
    fi

    return 1
}

resolve_images() {
    if [ -z "$SYSTEM_IMG" ]; then
        SYSTEM_IMG=$(find_latest_image "orin_nano_system_backup_*.img.gz" || true)
    fi

    if [ -z "$SYSTEM_IMG" ]; then
        error_exit "System image not found. Set SYSTEM_IMG or place image under BACKUP_DIR"
    fi

    if [ -z "$DATA_IMG" ]; then
        DATA_IMG=$(find_latest_image "orin_nano_data_backup_*.img.gz" || true)
    fi
}

check_file() {
    local file=$1
    local label=$2

    [ -f "$file" ] || error_exit "$label image file not found: $file"
    [ -r "$file" ] || error_exit "$label image file not readable: $file"

    local size_h
    size_h=$(du -h "$file" | awk '{print $1}')
    log "$label image ready: $file ($size_h)"
}

check_device() {
    local device=$1
    local label=$2

    [ -n "$device" ] || error_exit "$label target device is empty"
    [ -b "$device" ] || error_exit "$label target device not found: $device"
    [ -w "$device" ] || error_exit "$label target device not writable: $device"

    local mounted
    mounted=$(lsblk -nrpo NAME,MOUNTPOINT "$device" | awk 'NF>=2 && $2!="" {print $0}')
    if [ -n "$mounted" ]; then
        error_exit "$label target or its partitions are mounted, unmount first:\n$mounted"
    fi

    log "$label target device ready: $device"
}

validate_devices() {
    if [ -n "$DATA_DEVICE" ] && [ "$DATA_DEVICE" = "$SYSTEM_DEVICE" ]; then
        error_exit "DATA_DEVICE must be different from SYSTEM_DEVICE"
    fi
}

should_restore_data_device() {
    case "$ENABLE_DATA_RESTORE" in
        yes)
            if [ -z "$DATA_DEVICE" ] || [ -z "$DATA_IMG" ]; then
                error_exit "ENABLE_DATA_RESTORE=yes requires DATA_DEVICE and DATA_IMG"
            fi
            return 0
            ;;
        no)
            return 1
            ;;
        auto)
            if [ -n "$DATA_DEVICE" ] && [ -b "$DATA_DEVICE" ] && [ -n "$DATA_IMG" ]; then
                return 0
            fi
            return 1
            ;;
        *)
            error_exit "ENABLE_DATA_RESTORE only supports auto|yes|no"
            ;;
    esac
}

verify_checksum() {
    local file=$1
    local sidecar="${file}.md5"

    if [ ! -f "$sidecar" ]; then
        if [ "$STRICT_CHECKSUM" = "yes" ]; then
            error_exit "Checksum sidecar not found: $sidecar"
        fi
        log "Checksum sidecar not found, skipped because STRICT_CHECKSUM=no"
        return
    fi

    log "Verifying checksum via sidecar: $sidecar"
    if md5sum -c "$sidecar" --status >/dev/null 2>&1; then
        log "Checksum verification passed"
        return
    fi

    # Fallback: compare hash only, useful when image path changed after backup.
    local expected actual
    expected=$(awk '{print $1; exit}' "$sidecar")
    actual=$(md5sum "$file" | awk '{print $1}')

    if [ "$expected" = "$actual" ]; then
        log "Checksum verification passed (hash-only fallback)"
        return
    fi

    if [ "$STRICT_CHECKSUM" = "yes" ]; then
        error_exit "Checksum verification failed: $file"
    fi
    log "Checksum verification failed but STRICT_CHECKSUM=no, continue"
}

get_meta_value() {
    local image_file=$1
    local key=$2
    local meta_file="${image_file}.meta"

    [ -f "$meta_file" ] || return 1
    awk -F'=' -v k="$key" '$1==k {print $2}' "$meta_file" | head -n 1
}

check_target_size() {
    local image_file=$1
    local device=$2
    local label=$3

    local source_size_bytes
    source_size_bytes=$(get_meta_value "$image_file" "SOURCE_SIZE_BYTES" || true)

    if [ -z "$source_size_bytes" ]; then
        log "No SOURCE_SIZE_BYTES in ${image_file}.meta, skip size pre-check"
        return
    fi

    local target_size_bytes
    target_size_bytes=$(blockdev --getsize64 "$device" 2>/dev/null || true)
    [ -n "$target_size_bytes" ] || error_exit "Cannot read target size for $device"

    if [ "$target_size_bytes" -lt "$source_size_bytes" ]; then
        error_exit "$label target too small: target=${target_size_bytes}B source=${source_size_bytes}B"
    fi

    log "$label target size check passed"
}

restore_device() {
    local image_file=$1
    local device=$2
    local label=$3

    log "Start restoring $label"
    log "Image: $image_file"
    log "Target: $device"

    verify_checksum "$image_file"
    check_target_size "$image_file" "$device" "$label"

    if gunzip -c "$image_file" | dd of="$device" bs=4M status=progress conv=fsync 2>>"$LOG_FILE"; then
        log "$label restore finished"
    else
        error_exit "$label restore failed"
    fi
}

confirm_or_exit() {
    if [ "$ASSUME_YES" = "yes" ]; then
        log "ASSUME_YES=yes, skip interactive confirmation"
        return
    fi

    echo
    echo "DANGEROUS OPERATION"
    echo "This will overwrite all data on target devices."
    echo "  System target: $SYSTEM_DEVICE"
    if [ "$restore_data" = "true" ]; then
        echo "  Data target  : $DATA_DEVICE"
    fi
    echo

    read -r -p "Type YES to continue: " confirm
    if [ "$confirm" != "YES" ]; then
        log "Canceled by user"
        exit 0
    fi
}

main() {
    if [ "$EUID" -ne 0 ]; then
        echo "Please run as root (sudo)."
        exit 1
    fi

    check_dependencies
    check_backup_dir
    resolve_images

    [ -n "$SYSTEM_DEVICE" ] || error_exit "SYSTEM_DEVICE is required on host restore"
    validate_devices

    check_file "$SYSTEM_IMG" "System"
    check_device "$SYSTEM_DEVICE" "System"

    if [ -n "$DATA_IMG" ]; then
        check_file "$DATA_IMG" "Data"
    fi

    if should_restore_data_device; then
        check_device "$DATA_DEVICE" "Data"
        restore_data="true"
    else
        restore_data="false"
        log "Data restore disabled or requirements not met"
    fi

    log "BACKUP_DIR=$BACKUP_DIR"
    log "SYSTEM_IMG=$SYSTEM_IMG"
    log "SYSTEM_DEVICE=$SYSTEM_DEVICE"
    log "ENABLE_DATA_RESTORE=$ENABLE_DATA_RESTORE"
    log "STRICT_CHECKSUM=$STRICT_CHECKSUM"
    log "LOG_FILE=$LOG_FILE"
    if [ "$restore_data" = "true" ]; then
        log "DATA_IMG=$DATA_IMG"
        log "DATA_DEVICE=$DATA_DEVICE"
    fi

    confirm_or_exit

    restore_device "$SYSTEM_IMG" "$SYSTEM_DEVICE" "System"
    if [ "$restore_data" = "true" ]; then
        restore_device "$DATA_IMG" "$DATA_DEVICE" "Data"
    fi

    log "Sync disks"
    sync
    log "Restore completed"
    echo "Done. Log file: $LOG_FILE"
}

main "$@"
